# Generated by Django 4.1.3 on 2022-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=500, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'PaymentGatewaySetting',
                'verbose_name_plural': 'PaymentGatewaySettings',
                'db_table': 'paymentgatewaysettings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_id', models.CharField(max_length=15)),
                ('val_id', models.CharField(max_length=75)),
                ('card_type', models.CharField(max_length=150)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(max_length=55, null=True)),
                ('bank_tran_id', models.CharField(max_length=155, null=True)),
                ('status', models.CharField(max_length=55)),
                ('tran_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('card_issuer', models.CharField(max_length=255)),
                ('card_brand', models.CharField(max_length=15)),
                ('card_issuer_country', models.CharField(max_length=55)),
                ('card_issuer_country_code', models.CharField(max_length=55)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verify_sign', models.CharField(max_length=155)),
                ('verify_sign_sha2', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=15)),
                ('risk_title', models.CharField(max_length=25)),
            ],
        ),
    ]
